Update libMLIR_h with LLVM 20
EnzymeAD/Reactant.jl pull request #197
Opened 2024-10-25 21:42 UTC by Pangoraw

2024-10-25 21:48 UTC, Pangoraw commented
The generation is missing stablehlo header files which are needed before merging

2024-10-25 22:05 UTC, wsmoses commented
@mofeing honestly I’m confused why the api calls weren’t here to begin with.

when these were in the Yggdrasil build it should’ve exported every symbol we built into Julia headers so that implies to be that the header rn is wrong somehow…

2024-10-27 09:09 UTC, Pangoraw commented
so essentially replace this line: 

https://github.com/EnzymeAD/Reactant.jl/blob/a4f685cad9514a0d31b0df38658dafb5ce46b8c9/src/mlir/MLIR.jl#L12

with 

```julia
include("path/to/Reactant_jll/libMLIR_h.jl")
```
?

2024-10-27 09:16 UTC, mofeing commented
Wait, you should just rebuild "libMLIR_h.jl" locally by running:

```
bazel build //:libMLIR_h.jl
```

I just forgot to include that one in the `make-dialects.jl` script, so it regenerates automatically.

2024-10-27 09:28 UTC, Pangoraw commented
Ok so the new `make-dialects.jl` should be enough ? it automatically runs on each pr ?

2024-10-27 11:17 UTC, mofeing requested changes
This should be it. About your question, no: it doesn't run on each PR but on periodically every night and by manual dispatch. If you want, you can change the workflow to run on every PR but on 99% of the PRs it will do nothing.

EDIT: You can add a filter to the workflow such that it automatically runs on PRs that modify ReactantExtra.

2024-10-27 11:17 UTC, mofeing commented on src/mlir/IR/Type.jl
> +Type(T::Core.Type{<:Complex}; context=context()) = Type(API.mlirComplexTypeGet(Type(T(im) |> real |> typeof)))
This shouldn't be in this PR right?

2024-10-27 11:17 UTC, mofeing commented on deps/ReactantExtra/make-dialects.jl
> +src_dir = joinpath(@__DIR__, "..", "..", "src")
It's better if you use `dirname` instead of `".."` so that it works in non-posix systems like Windows.

2024-10-27 13:04 UTC, Pangoraw commented on src/mlir/IR/Type.jl
> +Type(T::Core.Type{<:Complex}; context=context()) = Type(API.mlirComplexTypeGet(Type(T(im) |> real |> typeof)))
#199

2024-10-27 13:51 UTC, mofeing approved these changes

2024-10-27 13:53 UTC, merged