refactor: use Ops instead of direct stablehlo calls
EnzymeAD/Reactant.jl pull request #347
Opened 2024-12-09 11:51 UTC by avik-pal

2024-12-09 13:28 UTC, mofeing commented on src/TracedRArray.jl
> +TracedRArray{T,N}(rhs::AbstractArray{T0,N}) where {T0,T,N} = Ops.constant(collect(rhs))
maybe can we implement `Base.convert` here too?

2024-12-09 13:36 UTC, mofeing requested changes

2024-12-09 13:36 UTC, mofeing commented on src/TracedRArray.jl
> +    set_mlir_data!(A, Ops.conj(materialize_traced_array(A)).mlir_data)
Please, don't remove the implementations for `Base.conj`. Ops are inheritly "out-place", so just calling them work straightforward.

2024-12-09 16:32 UTC, avik-pal commented on src/TracedRArray.jl
> +TracedRArray{T,N}(rhs::AbstractArray{T0,N}) where {T0,T,N} = Ops.constant(collect(rhs))
yeah, done!

2024-12-09 16:53 UTC, mofeing approved these changes

2024-12-10 07:14 UTC, wsmoses commented on src/utils.jl
>  function transpose_val(val)
okay this one is more of a utility so I'm honestly fine leaving this at a lower level without constructing a tracedrarray since it takes an mlir.value input and does an mlir.value output

2024-12-10 07:14 UTC, wsmoses approved these changes

2024-12-11 07:00 UTC, merged