Generalize broadcast
EnzymeAD/Reactant.jl pull request #35
Opened 2024-06-29 18:39 UTC by wsmoses

2024-06-30 14:21 UTC, wsmoses commented
Companion PR to https://github.com/EnzymeAD/Enzyme/pull/1952

Untested, but should enable arbitrary broadcast support (if all scalar functions are overloaded)

2024-07-01 15:35 UTC, mofeing commented on src/Reactant.jl
> +@inline function make_tracer(seen::IdDict, prev::RT, path, mode, data; toscalar=false, tobatch=nothing) where {RT}
What do these kwargs do?

2024-07-06 04:42 UTC, wsmoses commented on src/Reactant.jl
> +@inline function make_tracer(seen::IdDict, prev::RT, path, mode, data; toscalar=false, tobatch=nothing) where {RT}
whether the tracer we create should automatically change all arrays to scalars, or scalars to arrays

2024-07-06 21:17 UTC, mofeing requested changes
Just some fix requests and a couple of aesthetic suggestions.

Also, we should add a test for this.

2024-07-06 21:17 UTC, mofeing commented on src/overloads.jl
> +function elem_apply(f, args::VarArgs{Nargs})
Need `where` here:
```suggestion
function elem_apply(f, args::VarArgs{Nargs}) where {Nargs}
```

2024-07-06 21:17 UTC, mofeing commented on src/utils.jl
> +function make_mlir_fn(mod, f, args, kwargs, name="main", concretein=true; toscalar=false)
Maybe we could turn `name` and `concretein` into kwargs?
```suggestion
function make_mlir_fn(mod, f, args, kwargs; name="main", concretein=true, toscalar=false)
```

2024-07-06 21:17 UTC, mofeing commented on src/overloads.jl
> +    mod = MLIR.IR.module()
```suggestion
    mod = MLIR.IR.mmodule()
```

2024-07-06 21:17 UTC, mofeing commented on src/overloads.jl
> +    end
This should be declared out of `elem_apply`'s definition if it's not capturing any variable.

2024-07-10 20:22 UTC, avik-pal commented
https://github.com/EnzymeAD/Reactant.jl/blob/5134fe0d2bb6f6d7a4f72c1f0e2d996fe744d0f9/deps/clang#L2 need to be generalized?

2024-07-10 20:51 UTC, avik-pal commented on src/overloads.jl
> +        OutShape size(k)
```suggestion
        OutShape = size(k)
```

2024-07-14 01:17 UTC, merged