precompile first interpretation
EnzymeAD/Reactant.jl pull request #353
Opened 2024-12-09 19:57 UTC by glou-nes

Partial fix #348
remove a assertion in XLA. Get some result.

```
julia> x = Reactant.to_rarray(ones(3))
3-element ConcreteRArray{Float64, 1}:
 1.0
 1.0
 1.0

julia> @time @jit x .+ 3
 13.181369 seconds (36.25 M allocations: 1.830 GiB, 7.35% gc time, 99.76% compilation time: 1% of which was recompilation)
3-element ConcreteRArray{Float64, 1}:
 4.0
 4.0
 4.0
```
Use `SnoopCompile` to track invalidation, get several invalidation in the abstract interpreter. I already get similar invalidation because of REPL abstract interpreter in Julia 1.12. I don't know how to fix it. Some in the list are probably easier to handle.
```
lock_mi_inference(interp::GPUCompiler.GPUInterpreter, mi::Core.MethodInstance) @ GPUCompiler /depot/packages/GPUCompiler/GnbhK/src/jlgen.jl:405
unlock_mi_inference(interp::GPUCompiler.GPUInterpreter, mi::Core.MethodInstance) @ GPUCompiler /depot/packages/GPUCompiler/GnbhK/src/jlgen.jl:406
add_remark!(interp::GPUCompiler.GPUInterpreter, sv::Core.Compiler.InferenceState, msg) @ GPUCompiler /depot/packages/GPUCompiler/GnbhK/src/jlgen.jl:408
may_compress(interp::GPUCompiler.GPUInterpreter) @ GPUCompiler /depot/packages/GPUCompiler/GnbhK/src/jlgen.jl:413
may_discard_trees(interp::GPUCompiler.GPUInterpreter) @ GPUCompiler /depot/packages/GPUCompiler/GnbhK/src/jlgen.jl:414
verbose_stmt_info(interp::GPUCompiler.GPUInterpreter) @ GPUCompiler /depot/packages/GPUCompiler/GnbhK/src/jlgen.jl:415
abstract_call_known(interp::Enzyme.Compiler.Interpreter.EnzymeInterpreter{Handler}, f, arginfo::Core.Compiler.ArgInfo, si::Core.Compiler.StmtInfo, sv::Union{Core.Compiler.IRInterpretationState, Core.Compiler.InferenceState}, max_methods::Int64) where Handler @ Enzyme.Compiler.Interpreter /depot/packages/Enzyme/6C71q/src/compiler/interpreter.jl:906
inlining_policy(interp::Enzyme.Compiler.Interpreter.EnzymeInterpreter, src, info::Core.Compiler.CallInfo, stmt_flag::UInt32) @ Enzyme.Compiler.Interpreter /depot/packages/Enzyme/6C71q/src/compiler/interpreter.jl:427
get_inference_cache(interp::REPL.REPLCompletions.REPLInterpreter) @ REPL.REPLCompletions /code/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:569
ifelse(pred::Reactant.TracedRNumber{Bool}, x::Reactant.TracedRNumber{T}, y::Reactant.TracedRNumber{T}) where T @ Reactant /depot/dev/Reactant/src/TracedRNumber.jl:198
active_reg_inner(::Type{Reactant.TracedRArray{T, N}}, seen::ST, world::Union{Nothing, UInt64}, ::Val{justActive}, ::Val{UnionSret}) where {ST, T, N, justActive, UnionSret} @ Reactant /depot/dev/Reactant/src/TracedRArray.jl:418
active_reg_inner(::Type{Reactant.TracedRArray{T, N}}, seen::ST, world::Union{Nothing, UInt64}, ::Val{justActive}) where {ST, T, N, justActive} @ Reactant /depot/dev/Reactant/src/TracedRArray.jl:418
active_reg_inner(::Type{Reactant.TracedRArray{T, N}}, seen::ST, world::Union{Nothing, UInt64}) where {ST, T, N} @ Reactant /depot/dev/Reactant/src/TracedRArray.jl:418
kwcall(::NamedTuple, ::typeof(printstyled), io::Base.AnnotatedIOBuffer, msg...) @ StyledStrings.Legacy /code/usr/share/julia/stdlib/v1.11/StyledStrings/src/legacy.jl:126
write(filename::String, jit::Reactant.MLIR.IR.ExecutionEngine) @ Reactant.MLIR.IR /depot/dev/Reactant/src/mlir/IR/ExecutionEngine.jl:59
peek(io::StringEncodings.StringDecoder) @ YAML /depot/packages/YAML/XZZ1Y/src/buffered_input.jl:78
displaysize(t::REPL.Terminals.UnixTerminal) @ REPL.Terminals /code/usr/share/julia/stdlib/v1.11/REPL/src/Terminals.jl:153
displaysize(::REPL.Terminals.TextTerminal) @ REPL.Terminals /code/usr/share/julia/stdlib/v1.11/REPL/src/Terminals.jl:48
convert(::Type{Reactant.TracedRNumber{T}}, x::Number) where T @ Reactant /depot/dev/Reactant/src/TracedRNumber.jl:56
*(a::ObjectFile.fixed_string, b::String) @ ObjectFile /depot/packages/ObjectFile/eLzIt/src/string_utils.jl:52
lookup(ip::UInt64) @ Profile /code/usr/share/julia/stdlib/v1.11/Profile/src/Profile.jl:45
convert(::Type{Ptr{T}}, val::LLVM.GenericValue) where T @ LLVM /depot/packages/LLVM/wMjUU/src/execution.jl:103
show(io::IO, c::Base.AnnotatedChar) @ StyledStrings /code/usr/share/julia/stdlib/v1.11/StyledStrings/src/io.jl:286
ci_cache_token(job::GPUCompiler.CompilerJob{<:Any, <:Enzyme.Compiler.AbstractEnzymeCompilerParams}) @ Enzyme.Compiler /depot/packages/Enzyme/6C71q/src/compiler.jl:1203
kwcall(::NamedTuple, ::typeof(GPUCompiler.codegen), output::Symbol, job::GPUCompiler.CompilerJob{<:Enzyme.Compiler.EnzymeTarget}) @ Enzyme.Compiler /depot/packages/Enzyme/6C71q/src/compiler.jl:3223
get_inference_world(interp::REPL.REPLCompletions.REPLInterpreter) @ REPL.REPLCompletions /code/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:568
may_optimize(::REPL.REPLCompletions.REPLInterpreter) @ REPL.REPLCompletions /code/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:573
get_interpreter(job::GPUCompiler.CompilerJob{<:Any, <:Enzyme.Compiler.AbstractEnzymeCompilerParams}) @ Enzyme.Compiler /depot/packages/Enzyme/6C71q/src/compiler.jl:1212
eltype(::Type{<:EnzymeCore.RArray{T}}) where T @ EnzymeCore /depot/packages/EnzymeCore/15Zff/src/EnzymeCore.jl:740
convert(::Type{Array{T, N}}, X::Enzyme.TupleArray{T, Shape, Length, N}) where {T, Shape, Length, N} @ Enzyme /depot/packages/Enzyme/6C71q/src/sugar.jl:455
runtime_module(::GPUCompiler.CompilerJob{<:Any, <:Enzyme.Compiler.AbstractEnzymeCompilerParams}) @ Enzyme.Compiler /depot/packages/Enzyme/6C71q/src/compiler.jl:1185
promote_rule(::Type{T}, ::Type{Reactant.TracedRNumber{S}}) where {T, S} @ Reactant /depot/dev/Reactant/src/TracedRNumber.jl:52
print(io::IO, s::Union{Base.AnnotatedString, SubString{<:Base.AnnotatedString}}) @ StyledStrings /code/usr/share/julia/stdlib/v1.11/StyledStrings/src/io.jl:261
==(lhs, rhs::Reactant.TracedRNumber{T}) where T @ Reactant /depot/dev/Reactant/src/TracedRNumber.jl:166
print(io::IO, c::Base.AnnotatedChar) @ StyledStrings /code/usr/share/julia/stdlib/v1.11/StyledStrings/src/io.jl:284
convert(::Type{T}, x::Union{ConcreteRArray{T, 0}, ConcreteRNumber{T}}) where T @ Reactant /depot/dev/Reactant/src/ConcreteRArray.jl:126
Core.Compiler.InferenceParams(interp::REPL.REPLCompletions.REPLInterpreter) @ REPL.REPLCompletions /code/usr/share/julia/stdlib/v1.11/REPL/src/REPLCompletions.jl:566
==(lhs::Reactant.TracedRNumber{T}, rhs) where T @ Reactant /depot/dev/Reactant/src/TracedRNumber.jl:157
```

2024-12-09 20:10 UTC, mofeing reviewed
Thanks!

Would you mind providing comptimes of first interpretation before and after this PR? Times can vary between machines.

> Use SnoopCompile to track invalidation, get several invalidation in the abstract interpreter.

Yeah, that's why there's still time expent on compilation on 2nd, 3rd, ... calls to `@code_hlo`. But that's an issue for another PR.

2024-12-09 20:10 UTC, mofeing commented on Project.toml
> +PrecompileTools = "1.2.1"
Do we need to be so exact with the compat version? I prefer leaving it as open as we can to avoid compat conflicts with other libs.

2024-12-09 20:10 UTC, mofeing commented on src/precompile.jl
> +        @jit sum(x)
Don't do `@jit` but `@code_hlo optimize=false`. Problem is first interpretation so just tracing, not compilation.

Also, would you mind checking if `XLA.__init__()` and `Reactant.__init__()` are still required with `@code_hlo optimize=false`? I feel a lil bit nervous with them due to relocation.

Furthermore, it might be more interesting to use `GPUCompiler.precompile` as @vchuravy suggested to me because the interpreter we used is based on GPUCompiler.

2024-12-09 20:10 UTC, mofeing commented on src/XLA.jl
> +    #@assert cpuclientcount[] == 0
mmm is this ok @wsmoses?

2024-12-09 20:12 UTC, mofeing commented on src/XLA.jl
> +    #@assert cpuclientcount[] == 0
also, why is this assert failing?

2024-12-09 20:19 UTC, glou-nes commented on Project.toml
> +PrecompileTools = "1.2.1"
will relax it

2024-12-09 20:21 UTC, glou-nes commented on src/XLA.jl
> +    #@assert cpuclientcount[] == 0
I suppose precompile store the global value. Probably fix with `@code_hlo`

2024-12-09 22:37 UTC, wsmoses commented on src/precompile.jl
> +    XLA.__init__()
can we do this without init and just making our own cpuclient?

2024-12-09 22:37 UTC, wsmoses commented on src/precompile.jl
> +    XLA.__init__()
and ideally registry

2024-12-09 22:37 UTC, wsmoses commented on src/precompile.jl
> +    XLA.__init__()
this would avoid some of the weird "globals" problems in precompilation

2024-12-09 22:38 UTC, wsmoses commented on src/precompile.jl
> +        @jit sum(x)
it actually is not based on gpucompiler (the enzyme interp is not a descendant of gpuinterpreter)

2024-12-09 22:39 UTC, wsmoses commented on src/precompile.jl
> +    XLA.__init__()
in particular if used we need to carefully init and uninit globals: https://github.com/JuliaGPU/GPUCompiler.jl/blob/a94e6e2b7102f18e4b9aa08c623357a79ac62486/src/precompile.jl#L40

2024-12-09 22:49 UTC, mofeing commented on src/precompile.jl
> +    XLA.__init__()
yeah, like some kind of `MockClient` right?

2024-12-09 22:55 UTC, wsmoses commented on src/precompile.jl
> +    XLA.__init__()
I mean we could literally make a real Cpuclient which isn’t the global client, and make sure to free it

2024-12-10 07:57 UTC, mofeing commented
so i just tried and check that just calling `Base.code_ircode` is sufficient, so we don't need any Client to initialize and deinitialize.

```julia
julia> interp = Reactant.ReactantInterpreter()

julia> @time Base.code_ircode(sum, (Reactant.TracedRArray{Float64,2},); interp)
 52.089402 seconds (101.97 M allocations: 5.132 GiB, 2.34% gc time, 100.00% compilation time)
...

julia> @time Base.code_ircode(sum, (Reactant.TracedRArray{Float64,2},); interp)
  0.000488 seconds (1.53 k allocations: 67.750 KiB, 92.79% compilation time)
...

julia> @time Base.code_ircode(*, (Reactant.TracedRArray{Int64,2},Reactant.TracedRArray{Int64,2}); interp)
  0.829383 seconds (659.11 k allocations: 33.190 MiB, 99.99% compilation time)
...
```

2024-12-10 08:09 UTC, wsmoses commented
Bear in mind as well though that the absint will (hopefully) cache between calls

2024-12-10 08:26 UTC, glou-nes commented on src/precompile.jl
> +    XLA.__init__()
I tried using `ScopedValue` to proper deal with `XLA.Client`. But it's quite instable.

2024-12-10 08:29 UTC, wsmoses commented on src/precompile.jl
> +    XLA.__init__()
ConcreteRArray and related constructors should take an optional client argument

2024-12-10 08:56 UTC, glou-nes commented on src/precompile.jl
> +    XLA.__init__()
Using the client argument works extremely well. It goes down to 3s for `@code_hlo`. I just need now to deal with Client finalizer.

2024-12-10 12:05 UTC, mofeing commented on src/precompile.jl
> +    XLA.__init__()
You don't need to use the client if you just do the `Base.code_ircode` I explained below.

2024-12-10 12:26 UTC, glou-nes commented
```
@setup_workload begin
    @compile_workload begin
        Reactant.__init__()
        cpu = XLA.CPUClient()
        x = Reactant.ConcreteRArray(randn(Float64, 2, 2); client=cpu)
        @code_hlo optimize = false sum(x)
    end

    @compile_workload begin
        interp = Reactant.ReactantInterpreter()
        Base.code_ircode(sum, (Reactant.TracedRArray{Float64,2},); interp)
    end
end
```

I test the precompile with the following:

```
using Reactant.XLA
cpu = XLA.CPUClient()
x = Reactant.ConcreteRArray(randn(Float64, 2, 2); client=cpu)
t = @elapsed @code_hlo sum(x)
```
I suppose we can use both of them.
| Compile Workload    | Time |
| -------- | ------- |
|code_hlo 1  | 5.28    |
|Abstract Interpreter 2 | 6.99     |
| 1 + 2    | 5.14    |

2024-12-10 13:35 UTC, mofeing requested changes

2024-12-10 13:35 UTC, mofeing commented on src/precompile.jl
> +
This is not required if you do the other `@compile_workload`
```suggestion
```

2024-12-10 14:10 UTC, glou-nes commented on src/precompile.jl
> +
Probably the first one is better, following wsmoses remark, this doesn't use globals but MLIR registry.

2024-12-10 14:24 UTC, mofeing approved these changes
Everything's fine from my side then. I'm approving but you need to fix the tests first. There is a problem with the file Enzyme.jl which is quite weird because you haven't touch it? dialects? (Nightly and ubuntu x86-32 bits are ok to fail)

2024-12-10 20:06 UTC, wsmoses commented
So the direct call to ircode is about to get removed, so this should ideally do the codehlo call or equivalent

2024-12-10 21:52 UTC, mofeing commented
> So the direct call to ircode is about to get removed, so this should ideally do the codehlo call or equivalent

ah really? do we have another mechanism now?

2024-12-11 19:45 UTC, glou-nes commented
@mofeing I got errors for macOS 'ERROR: LoadError: StackOverflowError' and the strange Enzyme one with 1.10.  Should we use precompilation only with julia 1.11 and excluding MacOS?

2024-12-11 20:34 UTC, mofeing commented
> @mofeing I got errors for macOS 'ERROR: LoadError: StackOverflowError' and the strange Enzyme one with 1.10. Should we use precompilation only with julia 1.11 and excluding MacOS?

mmm in what arch? I just tried in aarch64-macos and got another error

also CI says that there are also problems in linux

```julia
julia> @jit sum(a)
Internal error: encountered unexpected error in runtime:
MethodError(f=Core.Compiler.:(⊑), args=(Core.Compiler.JLTypeLattice(), (:stmt, :line), Core.TypeofBottom()), world=0x00000000000015ac)
jl_method_error_bare at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:2208
jl_method_error at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:2226
jl_lookup_generic_ at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:3058 [inlined]
ijl_apply_generic at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:3073
⊑ at ./compiler/typelattice.jl:530
⊑ at ./compiler/typelattice.jl:508
⊑ at ./compiler/typelattice.jl:397 [inlined]
reprocess_instruction! at ./compiler/ssair/irinterp.jl:169
#_ir_abstract_constant_propagation#511 at ./compiler/ssair/irinterp.jl:251
_ir_abstract_constant_propagation at ./compiler/ssair/irinterp.jl:206
ir_abstract_constant_propagation at ./compiler/ssair/irinterp.jl:384
semi_concrete_eval_call at ./compiler/abstractinterpretation.jl:1168
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:812
abstract_call_method_with_const_args at ./compiler/abstractinterpretation.jl:788
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:103
abstract_call_known at ./compiler/abstractinterpretation.jl:2087
abstract_call at ./compiler/abstractinterpretation.jl:2169
abstract_call at ./compiler/abstractinterpretation.jl:2162
abstract_call at ./compiler/abstractinterpretation.jl:2354
abstract_eval_call at ./compiler/abstractinterpretation.jl:2370
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2380
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2624
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2913
typeinf_local at ./compiler/abstractinterpretation.jl:3098
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3186
_typeinf at ./compiler/typeinfer.jl:247
typeinf at ./compiler/typeinfer.jl:216
typeinf_edge at ./compiler/typeinfer.jl:930
abstract_call_method at ./compiler/abstractinterpretation.jl:629
abstract_call_gf_by_type at ./compiler/abstractinterpretation.jl:95
abstract_call_unknown at ./compiler/abstractinterpretation.jl:2156
abstract_call at ./compiler/abstractinterpretation.jl:2166
abstract_call at ./compiler/abstractinterpretation.jl:2162
abstract_call at ./compiler/abstractinterpretation.jl:2354
abstract_eval_call at ./compiler/abstractinterpretation.jl:2370
abstract_eval_statement_expr at ./compiler/abstractinterpretation.jl:2380
abstract_eval_statement at ./compiler/abstractinterpretation.jl:2624
abstract_eval_basic_statement at ./compiler/abstractinterpretation.jl:2889
typeinf_local at ./compiler/abstractinterpretation.jl:3098
typeinf_nocycle at ./compiler/abstractinterpretation.jl:3186
_typeinf at ./compiler/typeinfer.jl:247
typeinf at ./compiler/typeinfer.jl:216
typeinf_ext at ./compiler/typeinfer.jl:1051
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1082
typeinf_ext_toplevel at ./compiler/typeinfer.jl:1078
jfptr_typeinf_ext_toplevel_35906.1 at /Users/mofeing/.julia/juliaup/julia-1.10.7+0.aarch64.apple.darwin14/lib/julia/sys.dylib (unknown line)
_jl_invoke at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:3077
jl_apply at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/./julia.h:1982 [inlined]
jl_type_infer at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:394
jl_generate_fptr_impl at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/jitlayers.cpp:504
jl_compile_method_internal at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:2481
_jl_invoke at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:2887 [inlined]
ijl_apply_generic at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:3077
#make_mlir_fn#25 at /Users/mofeing/Developer/Reactant.jl/src/utils.jl:120
make_mlir_fn at /Users/mofeing/Developer/Reactant.jl/src/utils.jl:40 [inlined]
#10 at /Users/mofeing/Developer/Reactant.jl/src/Compiler.jl:295 [inlined]
block! at /Users/mofeing/Developer/Reactant.jl/src/mlir/IR/Block.jl:201
#9 at /Users/mofeing/Developer/Reactant.jl/src/Compiler.jl:294 [inlined]
mmodule! at /Users/mofeing/Developer/Reactant.jl/src/mlir/IR/Module.jl:92
jfptr_mmoduleNOT._18679 at /Users/mofeing/.julia/compiled/v1.10/Reactant/p9PzF_pjiEo.dylib (unknown line)
_jl_invoke at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:3077
#compile_mlir!#8 at /Users/mofeing/Developer/Reactant.jl/src/Compiler.jl:291
compile_mlir! at /Users/mofeing/Developer/Reactant.jl/src/Compiler.jl:290 [inlined]
#34 at /Users/mofeing/Developer/Reactant.jl/src/Compiler.jl:698
context! at /Users/mofeing/Developer/Reactant.jl/src/mlir/IR/Context.jl:76
unknown function (ip: 0x13c96018b)
_jl_invoke at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:0 [inlined]
ijl_apply_generic at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30b1f605e/agent-cache/default-honeycrisp-XC9YQX9HH2.0/build/default-honeycrisp-XC9YQX9HH2-0/julialang/julia-release-1-dot-10/src/gf.c:3077
#compile_xla#33 at /Users/mofeing/Developer/Reactant.jl/src/Compiler.jl:695
compile_xla at /Users/mofeing/Developer/Reactant.jl/src/Compiler.jl:690 [inlined]
#compile#38 at /Users/mofeing/Developer/Reactant.jl/src/Compiler.jl:722
compile at /Users/mofeing/Developer/Reactant.jl/src/Compiler.jl:721
unknown function (ip: 0x12effc077)
_jl_invoke at /Users/julia/.julia/scratchspaces/a66863c6-20e8-4ff4-8a62-49f30 [...]

2024-12-11 20:48 UTC, mofeing commented
but yeah, it's ok to disable for macOS on Julia 1.10 if you can't make it work
just open an issue so we remember that this is a known issue

also, does this happen for all OS in Julia 1.10? if so, then it's probably sth that we can't solve. but if it just happens, then it might a bug and we should report

2024-12-11 21:02 UTC, glou-nes commented
I was just looking to [Julia 1.11 - integration - ubuntu-20.04 - x64 - packaged libReactant - assertions=false - pull_request]. Right there is several kinds of error. For instance, one get 'ParseError' with [Julia 1.10 - neural_networks - macOS-latest - x64].  I manage to reproduce a error locally. It occurs when I use 'Pkg.test()' simple usage work correctly.

2024-12-12 13:47 UTC, mofeing commented
CI is still not working... and the issue seems to be coverage? It's very weird that you're having a `ParseError`, but the erroring file is `/Users/runner/work/Reactant.jl/Reactant.jl/src/mlir/Dialects/Enzyme.jl.2696.cov:4`, which seems to be produced by coverage.

I have tried it out locally and works so... very weird. @glou-nes do you mind asking in Slack's #github-actions channel maybe?

2024-12-12 16:46 UTC, mofeing commented
lol, so it seems like there is a bug in PrecompileTools with coverage?

2024-12-12 17:03 UTC, glou-nes commented
For which one do you find that? I don't understand why it's failing in so many different ways.  @mofeing I think I don't understand the problem enough to provide a useful reduced reproducer for #github-actions. Do you know which checks must success?

2024-12-12 18:50 UTC, mofeing commented
so you should check all the combinations that fulfill "ubuntu or macos, x64, Julia 1.10 or 1.11"

> For which one do you find that?

so in this commit from you https://github.com/EnzymeAD/Reactant.jl/pull/353/commits/8c5a1cfc76293ab721c57f19e993553da2fb29b8
you disable any code from PrecompileTools when testing, and it worked

do you mind trying to run an empty `@setup_workload` on CI?

2024-12-12 18:58 UTC, glou-nes commented
Sure! I wait this one using CI defined ENV to enable PrecompileTools. If that is working, I will move the logic inside of `@setup_workload`.

2024-12-14 10:23 UTC, mofeing requested changes
I think #377 fixes the problem between coverage and PrecompileTools.

I also reviewed some code to clean.

2024-12-14 10:23 UTC, mofeing commented on src/Reactant.jl
> +include("precompile.jl")
Can you rename to `Precompile.jl`? to keep consistency with file names

2024-12-14 10:23 UTC, mofeing commented on src/precompile.jl
> +    @info "enable precompilation" gethostname() Base.active_project()
```suggestion
```

2024-12-14 10:25 UTC, mofeing commented on src/precompile.jl
> +    @info "enable precompilation" gethostname() Base.active_project()
probably we don't need this anymore
```suggestion
```

2024-12-14 15:08 UTC, glou-nes commented
@mofeing only the covering one seems to be corrected. We still get `StackOverflow` for instance (https://github.com/EnzymeAD/Reactant.jl/actions/runs/12329253047). Is that acceptable to skip the CI with `PrecompilationTools` using the ENV workaround?

2024-12-14 16:50 UTC, wsmoses commented on src/XLA.jl
> -    cpuclientcount[] += 1
We should leave this, and instead we should after compile, manually free the CPU client then reset the global to 0. This is akin to what is done elsewhere as far as I know, e.g. https://github.com/JuliaGPU/GPUCompiler.jl/blob/a94e6e2b7102f18e4b9aa08c623357a79ac62486/src/precompile.jl#L40

2024-12-14 16:50 UTC, wsmoses commented on src/Precompile.jl
> +    end
We should explicitly free the client here

2024-12-14 16:51 UTC, wsmoses commented on src/Precompile.jl
> +        Reactant.__init__()
what else in init do we need here?

2024-12-14 17:09 UTC, glou-nes commented on src/Precompile.jl
> +        Reactant.__init__()
We need the dialect registry initialization.
```
function __init__()
    registry[] = MLIR.IR.DialectRegistry()
    @ccall MLIR.API.mlir_c.InitializeRegistryAndPasses(
        registry[]::MLIR.API.MlirDialectRegistry
    )::Cvoid
end
```

2024-12-14 17:10 UTC, glou-nes commented on src/XLA.jl
> -    cpuclientcount[] += 1
I don't understand, why we must keep only one client?

2024-12-14 17:11 UTC, wsmoses commented on src/Precompile.jl
> +        Reactant.__init__()
ah understood, can you refactor the init code to call a new initialize_dialect function, and also create a deinitialize_dialect routine which frees and resets the global registry? Then can we call that pair of functions here

2024-12-14 17:12 UTC, wsmoses commented on src/XLA.jl
> -    cpuclientcount[] += 1
I think (but might be misremembering) that XLA blew up with more than two concurrent CPU clients, at least on the same device. Maybe that's no longer the case though

2024-12-14 17:14 UTC, wsmoses commented on src/Precompile.jl
> +        Reactant.__init__()
The reason I'm being extra careful all over the place here, is these functions create pointers specific to a specific julia runtime invocation. Which if we open a new julia session, may no longer be valid (and cause extremely bad issues)

2024-12-14 17:15 UTC, wsmoses commented on src/Precompile.jl
> +        Reactant.__init__()
Of course the reason being that precompilation is done advance in a potentially different julia session than where the ode is run

2024-12-14 17:18 UTC, glou-nes commented on src/Precompile.jl
> +        Reactant.__init__()
Sure, that is a robust approach. I add them!

2024-12-14 18:01 UTC, glou-nes commented on src/XLA.jl
> -    cpuclientcount[] += 1
It's easy to blew up it using two clients: 
```
xa = XArray(...,client=XLA.CPUClient())
xb = XArray(...,client=XLA.CPUClient())
@jit f(xa,xb)
```

2024-12-15 00:37 UTC, mofeing commented on src/XLA.jl
> +global cpuclientcount = Ref(0)
mmm why `global` and not `const` here?

2024-12-15 00:37 UTC, mofeing commented on src/Precompile.jl
> +    end
mmm i think we don't need this. like the error you were having when you removed where either because of coverage (which was solved in #377) or because deinitialization right?

2024-12-15 01:04 UTC, glou-nes commented on src/XLA.jl
> +global cpuclientcount = Ref(0)
typo, thank!

2024-12-15 01:06 UTC, glou-nes commented on src/Precompile.jl
> +    end
No idea, I'm retesting with the interpreter and the fixed MLIR init.

2024-12-15 04:09 UTC, glou-nes commented on src/Precompile.jl
> +    end
It seems to be needed, I suppose one got strange interaction between PrecompilationTools and Test environment. With Precompilation + Interp2, I get a new kind of error: full segfault (https://github.com/EnzymeAD/Reactant.jl/actions/runs/12334577561). The CI succeed with my ENV hack.

2024-12-15 14:00 UTC, mofeing commented
okay, so i think we shouldn't merge it as of the current state because it seems like using XLA clients and compiling MLIR code is not relocatable.

i've tried it locally and it segfaults, but if I replace the precompile statements for the `Base.code_ircode` call again, then it works and runs all tests except for "autodiff.jl", where it fails.

this is the result of running the tests (except for the crashing "autodiff.jl" tests)
```julia
...
Test Summary:     | Pass  Broken  Total      Time
Reactant.jl Tests | 1593      10   1603  14m04.4s
     Testing Reactant tests passed 
```

for "autodiff.jl" testsets, i'm getting this error:
```julia
Assertion failed: (static_cast<size_t>(std::distance(values.begin(), values.end())) == size() && "expected 'values' to correspond 1-1 with the number of results"), function replaceAllUsesWith, file ValueRange.h, line 284.

[46907] signal 6: Abort trap: 6
in expression starting at /Users/mofeing/Developer/Reactant.jl/test/autodiff.jl:7
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 16990417 (Pool: 16989833; Big: 584); GC: 13
ERROR: Package Reactant errored during testing (received signal: 6)
```

2024-12-15 14:28 UTC, mofeing commented
also, initialization, cpu instantiation and array allocation should be outside of `@compile_workload` no? like the only thing inside should be the `@code_hlo`

2024-12-15 15:50 UTC, wsmoses commented
I saw that assertion earlier debugging a test and I think it’s a bug in the test itself if we can isolate it

2024-12-15 20:19 UTC, glou-nes commented
@mofeing Thank you very much for the feedbacks! I try a last one with code_hlo and move on to code_ircode!

2024-12-16 13:54 UTC, glou-nes commented
@mofeing here we go again. New errors too `AssertionError(msg="malformed :new expression")`. I'm running out of idea. And I don't know who the culprit is, do you have some guess to where a issue can be open?

2024-12-16 20:19 UTC, glou-nes commented
time to bisect then!

2024-12-18 22:56 UTC, glou-nes commented
I bisect locally ~ 10 times and I get noisy results: several build failed for other reasons, as Gabriel said, it's probably a memory corruption. I will probably test to have a custom CI to manage this.

2025-01-03 23:34 UTC, wsmoses commented
I dived into this on a 1.10 debug build. It looks like there's some invalid state during deserialization (that at first glance appears to be a julia bug not one of ours).

2025-01-03 23:38 UTC, wsmoses commented
<img width="826" alt="Screenshot 2025-01-03 at 6 37 44 PM" src="https://github.com/user-attachments/assets/0143fae2-53ad-4aa6-8c81-88cb4a35cbb1" />

@gbaraldi @vchuravy any ideas what's happening here?

2025-01-03 23:49 UTC, wsmoses commented
This does trigger on different methods at different times, but I’m really confused how/why since presumably the serialization won’t change ?

2025-01-03 23:53 UTC, gbaraldi commented
Memory corruption?

2025-01-04 03:47 UTC, wsmoses commented
the (seemingly clearly busted) data is not written between loading the precompiled object and when it breaks. So precompilation is apparently creating a busted serialization?

 
<img width="525" alt="Screenshot 2025-01-03 at 10 45 43 PM" src="https://github.com/user-attachments/assets/208be966-b843-468a-8cd6-2c794fd433e9" />

<img width="831" alt="Screenshot 2025-01-03 at 10 45 03 PM" src="https://github.com/user-attachments/assets/c4322c40-0305-405e-ac77-f5a121d55ba7" />

2025-01-04 03:47 UTC, wsmoses commented
Also the fact that this is busted on 1.10 and not 1.11 [combined with the serialization itself being awry] makes me really think this is a Julia bug.

2025-01-04 05:53 UTC, merged